name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --pull --tag oisupport/perl-bashbrew .
      - uses: actions/checkout@v3
        with:
          repository: docker-library/official-images
          ref: abe06f9a56327c6b8805437a6ddc47b2e8a2de5f
          path: oi
      - run: echo "BASHBREW_LIBRARY=$PWD/oi/library" >> "$GITHUB_ENV"
      - run: docker run -dit --name registry --restart always -p 5000:5000 registry
      - run: ./test-localhost.sh
